name: Deploy

on:
  workflow_call:

jobs:
  update-deployment:
    name: Update Deployment
    runs-on: self-hosted

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          repository: pesca-dev/kneipolympics-deploy
          event-type: kneipolympics-deploy-trigger
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
